### ISSUE TITLE
Add ports to backendRuntime

### ISSUE THREAD

**Issue by kerthcet** [InftyAI/llmaz#270]
**What would you like to be added**:

Right now, we hard-coded the ports in the project, it's the service port:8080, however, some inference engines need to add more ports as needed, e.x. the sglang needs to expose the 20000 port for distributing communication when crossing nodes.

```yaml
            ports:
            - containerPort: 8000
              name: http
              protocol: TCP
            - containerPort: 20000
              name: distributed
              protocol: TCP
```

**Why is this needed**:

Suitable for more cases.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.
