### ISSUE TITLE
Change the envoy ai gateway to a stable version

### ISSUE THREAD

**Issue by kerthcet** [InftyAI/llmaz#414]
**What happened**:

Right now, we're using an unstable version of envoy, see helm chart.yaml:

```
  - name: gateway-helm
    version: 0.0.0-latest
    repository: "oci://registry-1.docker.io/envoyproxy"
    condition: envoy-gateway.enabled
  - name: ai-gateway-helm
    version: v0.0.0-latest
    repository: "oci://registry-1.docker.io/envoyproxy"
    condition: envoy-ai-gateway.enabled
```

However, Envoy AI gateway is changing rapidly, see the latest PR https://github.com/envoyproxy/ai-gateway/pull/599, service is no longer supported in AIServiceBackend, which is not used by us.
```
Due to the limitation of EG's extension server API, AIBackendService that references k8s Service 
cannot be supported so we have to drop the support for it. Since there's a workaround for it, 
it should be fine plus EG can be fixed easily so the version after the next release should be able to 
revive the support.
```

**What you expected to happen**:

I believe the latest version of Envoy AI gateway will not work smoothly with llmaz. But I haven't tried yet.

**How to reproduce it (as minimally and precisely as possible)**:

Reinstall the whole system with helm chart.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- llmaz version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kerthcet** [comment]
I'll take a try with the latest envoy ai gateway later.

**Comment by kerthcet** [comment]
The solution seems like creating a gateway backend instead, see basic.yaml:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: provider-fallback-always-failing-upstream
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: provider-fallback-always-failing-upstream.default.svc.cluster.local
        port: 443
```
