### ISSUE TITLE
Support Envoy AI gateway v0.2.0

### ISSUE THREAD

**Issue by kerthcet** [InftyAI/llmaz#463]
**What would you like to be cleaned**:

Envoy AI Gateway just released v0.2.0 days ago, which supports some features like customized ownedBy, created which is helpful to our project.

Also, it no longer supports service directly but the backends, which will impact our envoy ai gateway example in `docs/examples/envoy-ai-gateway`, basically, we should replace the service with the backend. See release note: https://aigateway.envoyproxy.io/release-notes/v0.2#%EF%B8%8F-breaking-changes

**Why is this needed**:

**Comment by googs1025** [comment]
> basically, we should replace the service with the backend.

Could you describe this in more detail? 

I'm following the api docs https://aigateway.envoyproxy.io/docs/api/#aigatewayrouterule , maybe we need to specify modelsOwnedBy and timeouts ?

```yaml
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: default-envoy-ai-gateway
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: default-envoy-ai-gateway
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: qwen2-0--5b
      backendRefs:
        - name: qwen2-0--5b
      modelsOwnedBy: "llmaz"
      timeouts:
        request: 3m
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: qwen2--5-coder
      backendRefs:
        - name: qwen2--5-coder
      modelsOwnedBy: "llmaz"
      timeouts:
        request: 3m
```

I'm not sure if it's appropriate to continue using backendRef: Service
 🤔 
```yaml
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: qwen2-0--5b
spec:
  schema:
    name: OpenAI
  backendRef:
    name: qwen2-0--5b-lb
    kind: Service
    port: 8080
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: qwen2--5-coder
spec:
  schema:
    name: OpenAI
  backendRef:
    name: qwen2--5-coder-lb
    kind: Service
    port: 8080
```
