### ISSUE TITLE
ollama support

### ISSUE THREAD

**Issue by kerthcet** [InftyAI/llmaz#91]
**What would you like to be added**:

ollama provides [sdk](https://github.com/ollama/ollama-python) for integrations, we can easily integrate with it, one of the benefits I can think of is ollama maintains a bunch of quantized models, we can leverage.

**Why is this needed**:

Ecosystem integration.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
Because of ollama doesn't provide http servers, one way to integrate with it is to support URI with ollama protocol and inference with llama.cpp

**Comment by qinguoyi** [comment]
i will finish this work util 11.2

**Comment by kerthcet** [comment]
Hey @qinguoyi if you have any design details, better to share in this issue, we can discuss about that to avoid unnecessary refactorings. Thanks！

**Comment by qinguoyi** [comment]
## Let we see some backgorund,
* how llmaz runs
  * First download the model file, and then infer based on the model file
* what ollama supports 
  * support run direct，which can load file from ollama self repo. 
  * support import custom model files, which is not in ollama repo. 
    * guff 
    * safetensors(import direct; import with tuned adapter)
    * quantizing other type model file

so,  **Considering the llmaz model, our goal is to support ollama importing custom model file inference，including guff and safetensors(import direct)**

## Let we see the difficult to impl,
https://github.com/ollama/ollama/blob/main/docs/import.md , according to the official docs, if we import custom model file, we need exec some shelll cmd after start ollama server:
* make the file named Modelfile
* ollama crate modelName -f Modelfile
* ollama run modelName

Let we see ollama offlical image cmd,
![image](https://github.com/user-attachments/assets/73d42bb4-a65e-4506-850a-4b40aabc8e3d)

according the image inspect, we can see  there is olny to start ollama server.
so, **The difficulty lies in how to execute multiple commands and import custom model files for inference while starting the image.**

## Let's see how to do it

If you want to execute multiple commands, try to use shell instead of other languages like python, because almost all images will have this command.

We have two containers, an init container for downloading models and a main container for starting the inference service; so, we have two solutions to implement it.
* The first one is to rebuild a new image based on the official image and inject the shell script into it. This is not flexible enough. If the official image is updated, we need to rebuild it.
* The second one is to add a logic to copy the script file to the models directory when the init container downloads the model, that is, the script directory is mounted to the models directory, so that it can be expanded for more scripts in the future.
* 
![image](https://github.com/user-attachments/assets/dbc74310-2b16-4d47-9d4e-a8057092fd2b)

In summary, **we choose the second method to implement it**. The specific script commands are as follows:
```shell
#!/bin/bash
# start ollama server
ollama serve &

# ensure server is normal
sleep 5

# check input params
if [ -z "$1" ]; then
    echo "please input GGUF model file path，such as：./start_ollama.sh /path/to/model.gguf"
    exit 1
fi

MODEL_PATH=$1

# judge input is file path or dir path
if [ -f "$MODEL_PATH" ]; then
    echo "input file path：$MODEL_PATH"
    # judge whether the path is suffix with .gguf or not  
    if [ -f "$MODEL_PATH" ]; then
        if [[ "$MODEL_PATH" == *.gguf ]]; then
            echo "file exist and suffix with .guff ：$MODEL_PATH"
        else
            echo "file exist but not suffix with .guff：$MODEL_PATH"
            eixt 1
        fi
    else
        echo "file is not exist：$MODEL_PATH"
        exit 1
    fi

elif [ -d "$MODEL_PATH" ]; then
       echo "input dir path：$MODEL_PATH"

    if [ -d "$MODEL_PATH" ]; then
        # judge whether has suffix with .safetensors in the dir or not 
        SAFETENSORS_FILES=$(find "$MODEL_PATH" -type f -name "*.safetensors")

        if [ -z "$SAFETENSORS_FILES" ]; then
            echo "dir exists but there no file suffix with .safetensors"
            exit 1
        else
            echo "dir exists and there has suffix with .safetensors in the dir："
            echo "$SAFETENSORS_FILES"
        fi
    else
        echo "dir is not exist：$MODEL_PATH"
        exit 1
    fi
else
    echo "input path is not file and not dir：$MODEL_PATH"
    exit 1
fi


# create modelfile
MODEL_FILE="Modelfile"
cat <<EOF > $MODEL_FILE
FROM "$MODEL_PATH"
EOF

echo "create modelfile success"
cat $MODEL_FILE

# run Ollama create
if [ -z "$2" ]; then
    echo "please input model name"
    exit 1
fi
MODEL_PATH=$2
ollama create $MODEL_PATH -f Modelfile
if [ $? -ne 0 ]; then
    echo "run ollama create occur error"
    exit 1
fi

# run Ollama run 
ollama run mymodel

# ensure the shell is not exit,avoid the process exit
while true; do
    sleep 3600
done
```

## Let we see the result,
Here we take the guff file mounting as an example. In order to start faster, we use the minimized image alpine/ollala:latest
* playground.yaml
```yaml
{{- if .Values.backendRuntime.install -}}
apiVersion: inference.llmaz.io/v1alpha1
kind: BackendRuntime
metadata:
  labels:
    app.kubernetes.io/name: backendruntime
    app.kubernetes.io/part-of: llmaz
    app.kubernetes.io/created-by: llmaz
  name: ollama
spec:
  commands:
    - sh
    - /workspace/models/llmaz-scripts/start_ollama.sh
  image: alpine/ollama
  version: latest
  # Do not edit the preset argument name unless you know what you're doing.
  # Free to add more arguments with your requirements.
  args:
    - name: default
      flags:
        - "{{`{{ .ModelPath }}`}}"
        - "{{`{{ .ModelName }}`}}"
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi
{{- end }}

```

Let us to port-forwrd the 11434 to 8080:
![image](https://github.com/user-attachments/assets/e0d0e5ba-4845-40e9-acba-90a5fa88b2aa)
![image](https://github.com/user-attachments/assets/13265768-c9fd-4a14-ad6c-237e68b16383)
![image](https://github.com/user-attachments/assets/b061beba-7700-4424-a4be-5feba49ec42c)

so, this is my idea to support ollama. i wolud like to know more idea to support elegant. PTAL @kerthcet
